---
- hosts: localhost
  connection: local
  tasks:
    - name: Ensure /tmp/app directory exists
      file:
        path: /tmp/app
        state: directory
        mode: '0755'

    - name: Copy binary to /tmp/app
      copy:
        src: /workspace/app/app
        dest: /tmp/app/app
        mode: '0755'
        backup: yes   # на всякий случай создаст бэкап, если файл уже есть